CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(254) NOT NULL,
  name VARCHAR(250) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email),
  CONSTRAINT check_user_email_len CHECK (LEN(email) >= 6 AND LEN(email) <= 254),
  CONSTRAINT check_user_name_len CHECK (LEN(name) >= 2 AND LEN(name) <= 250)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(250) NOT NULL,
  CONSTRAINT pk_cat PRIMARY KEY (id),
  CONSTRAINT uq_cat_name UNIQUE (name),
  CONSTRAINT check_cat_name_len CHECK (LEN(name) >= 1 AND LEN(name) <= 50)
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat NUMBER NOT NULL,
  lot NUMBER NOT NULL,
  CONSTRAINT pk_location PRIMARY KEY (id),
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT REFERENCES categories (id) NOT NULL,
  created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description VARCHAR(7000) NOT NULL,
  event_date TIMESTAMP NOT NULL,
  initiator_id BIGINT REFERENCES users (id) NOT NULL,
  location_id BIGINT REFERENCES locations (id) NOT NULL,
  paid BOOLEAN NOT NULL,
  participant_limit INTEGER NOT NULL,
  published_on TIMESTAMP,
  request_moderation BOOLEAN NOT NULL,
  state VARCHAR(255) NOT NULL,
  title VARCHAR(120) NOT NULL,
  CONSTRAINT pk_events PRIMARY KEY (id),
  CONSTRAINT check_event_annotation_len CHECK (LEN(annotation) >= 20 AND LEN(annotation) <= 2000),
  CONSTRAINT check_event_description_len CHECK (LEN(description) >= 20 AND LEN(description) <= 7000),
  CONSTRAINT check_event_title_len CHECK (LEN(title) >= 3 AND LEN(title) <= 120)
);
