CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(254) NOT NULL,
  name VARCHAR(250) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)б
  CONSTRAINT check_email_length CHECK (LEN(name) >= 6 AND LEN(email) <= 254),
  CONSTRAINT check_name_length CHECK (LEN(name) >= 2 AND LEN(name) <= 250)
);
